"""Slide role planning for the one-deck Version 10 gate."""

from __future__ import annotations

from dataclasses import replace

from .models import SlideDirectorDecision


def _decision(
    slide_no: int,
    section_id: str,
    slide_role: str,
    slide_purpose: str,
    audience_need: str,
    decision_support_role: str,
    priority_level: str,
    emphasis_level: str,
    estimated_minutes: float,
    must_include: tuple[str, ...],
    may_include: tuple[str, ...],
    must_not_include: tuple[str, ...],
    action_title_intent: str,
    diagram_intent: str,
    evidence_required: tuple[str, ...],
    emotion_target: str,
    transition_from_previous: str,
    transition_to_next: str,
    speaker_note_goal: str,
    removal_reason_if_optional: str = "",
    appendix_reason_if_moved: str = "",
) -> SlideDirectorDecision:
    return SlideDirectorDecision(
        slide_id=f"slide-{slide_no:02d}",
        slide_no=slide_no,
        section_id=section_id,
        slide_role=slide_role,
        slide_purpose=slide_purpose,
        audience_need=audience_need,
        decision_support_role=decision_support_role,
        priority_level=priority_level,  # type: ignore[arg-type]
        emphasis_level=emphasis_level,  # type: ignore[arg-type]
        estimated_minutes=estimated_minutes,
        must_include=must_include,
        may_include=may_include,
        must_not_include=must_not_include,
        action_title_intent=action_title_intent,
        diagram_intent=diagram_intent,
        evidence_required=evidence_required,
        emotion_target=emotion_target,
        transition_from_previous=transition_from_previous,
        transition_to_next=transition_to_next,
        speaker_note_goal=speaker_note_goal,
        removal_reason_if_optional=removal_reason_if_optional,
        appendix_reason_if_moved=appendix_reason_if_moved,
    )


def _renumber(slides: list[SlideDirectorDecision]) -> list[SlideDirectorDecision]:
    return [
        replace(slide, slide_no=index + 1, slide_id=f"slide-{index + 1:02d}")
        for index, slide in enumerate(slides)
    ]


def _adapt_to_page_budget(slides: list[SlideDirectorDecision], target_count: int | None) -> list[SlideDirectorDecision]:
    if target_count is None or target_count == len(slides):
        return _renumber(slides)

    by_role = {slide.slide_role: slide for slide in slides}
    short_order = [
        "cover",
        "executive_summary",
        "problem",
        "root_cause",
        "solution",
        "kpi",
        "roadmap",
        "risk",
        "governance",
        "decision",
        "roi",
        "poc_scope",
        "process",
        "appendix_evidence",
        "appendix_faq",
    ]
    if target_count < len(slides):
        selected = [by_role[role] for role in short_order[: max(1, target_count)] if role in by_role]
        if "decision" not in {slide.slide_role for slide in selected} and "decision" in by_role:
            selected[-1] = by_role["decision"]
        return _renumber(selected)

    selected = list(slides)
    extension_roles = ("appendix_evidence", "appendix_faq", "risk", "governance", "process", "kpi", "roi")
    index = 0
    while len(selected) < target_count:
        role = extension_roles[index % len(extension_roles)]
        selected.append(by_role[role])
        index += 1
    return _renumber(selected)


def plan_slide_roles(target_count: int | None = None) -> list[SlideDirectorDecision]:
    """Return the deterministic 15-slide PoC proposal sequence.

    This stays at deck-direction level. It plans purpose, order, emphasis,
    evidence placement, appendix movement, and speaker-note intent only.
    """

    slides = [
        _decision(
            1,
            "sec-01",
            "cover",
            "提案の主題と顧客名を明確化する",
            "この提案が自社向けであることを即時理解する",
            "会議の入口を整える",
            "hero",
            "medium",
            0.5,
            ("顧客名", "提案テーマ", "業務変革フロー"),
            (),
            ("詳細な説明文",),
            "画像認識AI導入提案",
            "業務変革フロー",
            ("customer_fact",),
            "期待感",
            "",
            "まず結論へ進む",
            "会議冒頭で顧客固有の提案であることを示す",
        ),
        _decision(
            2,
            "sec-01",
            "executive_summary",
            "提案の結論とPoC判断の流れを示す",
            "何を決める会議かを理解する",
            "PoC合意へ向けた全体判断を支援する",
            "hero",
            "peak",
            2.0,
            ("提案結論", "現状", "提案", "成果", "次の合意"),
            ("ROIは評価条件として扱う",),
            ("細かい出典", "技術仕様"),
            "AIで検品品質と処理速度を同時に高めます",
            "Current to Proposal to Outcome",
            ("hypothesis", "requires_confirmation"),
            "納得",
            "表紙の期待感を受け、会議の結論を先に示す",
            "次に課題構造の合意へ進む",
            "経営・部門責任者が2分で判断軸を持てるようにする",
        ),
        _decision(
            3,
            "sec-02",
            "problem",
            "判断ばらつきの構造を可視化する",
            "課題が単なる作業問題ではないと理解する",
            "課題構造への合意を取る",
            "key",
            "high",
            2.0,
            ("症状", "業務上の原因", "根本原因", "事業影響"),
            ("顧客ヒアリングで工程名を更新",),
            ("長い課題一覧",),
            "判定基準が人に閉じ、改善材料として蓄積されていません",
            "因果チェーン",
            ("customer_fact", "hypothesis"),
            "危機感",
            "結論の根拠として、なぜPoCが必要かを示す",
            "原因の深掘りへつなぐ",
            "現状課題を顧客と同じ言葉で確認する",
        ),
        _decision(
            4,
            "sec-02",
            "root_cause",
            "根本原因をPoC仮説へ変換する",
            "何を検証すべきかを理解する",
            "PoC対象の絞り込みを支援する",
            "key",
            "high",
            1.5,
            ("暗黙知", "記録分散", "判定ログ未活用"),
            ("実工程名",),
            ("責任追及に見える表現",),
            "原因は判定基準と記録が業務資産化されていないことです",
            "Fishbone / Issue Tree",
            ("hypothesis",),
            "危機感",
            "課題構造から根本原因へ絞る",
            "PoC範囲へつなぐ",
            "原因を責任論ではなく改善テーマとして説明する",
        ),
        _decision(
            5,
            "sec-03",
            "poc_scope",
            "PoCで検証する範囲を限定する",
            "どこまでを今回決めるか理解する",
            "過剰期待を抑え、合意しやすくする",
            "key",
            "medium",
            1.5,
            ("対象範囲", "対象外", "評価対象"),
            ("画像サンプル数",),
            ("本番全範囲の断定",),
            "PoCは検品の一部範囲に絞り、評価条件を先に合意します",
            "Scope Matrix",
            ("requires_confirmation",),
            "安心",
            "原因仮説を検証範囲へ落とす",
            "人とAIの役割へ進む",
            "今回決める範囲と決めない範囲を分ける",
        ),
        _decision(
            6,
            "sec-03",
            "solution",
            "人とAIの役割分担を示す",
            "現場運用の姿を理解する",
            "現場受容性を高める",
            "key",
            "high",
            2.0,
            ("AI一次判定", "人の例外確認", "判断ログ"),
            ("現場承認フロー",),
            ("AIが全判断する表現",),
            "AIは一次判定を担い、人は例外と最終判断に集中します",
            "Human + AI Role Split",
            ("hypothesis",),
            "期待",
            "PoC範囲を実際の役割へ変える",
            "処理フローへつなぐ",
            "AIを置き換えではなく補助として伝える",
        ),
        _decision(
            7,
            "sec-03",
            "process",
            "PoC業務フローを具体化する",
            "検証時の動きを理解する",
            "実行可能性を支援する",
            "support",
            "medium",
            1.8,
            ("画像取得", "AI判定", "人の確認", "記録"),
            ("既存システム連携",),
            ("詳細な画面仕様",),
            "業務フローは画像取得から判断ログ蓄積まで一気通貫にします",
            "Flow",
            ("hypothesis",),
            "安心",
            "役割分担を業務手順へ展開する",
            "評価指標へつなぐ",
            "営業担当がPoC当日の流れを説明できるようにする",
        ),
        _decision(
            8,
            "sec-03",
            "kpi",
            "PoC評価指標を3点に絞る",
            "何をもって成功とするか理解する",
            "評価条件の合意を支援する",
            "key",
            "peak",
            2.0,
            ("判定一致率", "検品時間", "再確認件数"),
            ("測定方法", "測定タイミング"),
            ("未確定値の断定",),
            "評価指標は精度・工数・再確認件数の3点に絞ります",
            "KPI Dashboard",
            ("customer_fact", "requires_confirmation"),
            "納得",
            "PoC手順を評価条件へ変える",
            "ロードマップへつなぐ",
            "現時点の数値は仮説と確認事項を分ける",
        ),
        _decision(
            9,
            "sec-04",
            "roadmap",
            "8週間の検証手順を示す",
            "いつ何を判断するか理解する",
            "実施可否の判断を支援する",
            "support",
            "medium",
            2.0,
            ("準備", "検証", "評価", "判断"),
            ("キックオフ日",),
            ("細かいタスク表",),
            "8週間で検証し、本番判断に必要な材料を揃えます",
            "Timeline",
            ("customer_fact",),
            "安心",
            "KPIを測る時間軸へ展開する",
            "ROI評価へつなぐ",
            "期間内で判断材料を揃える流れを説明する",
        ),
        _decision(
            10,
            "sec-04",
            "roi",
            "投資判断の見方を示す",
            "費用ではなく回収観点で理解する",
            "投資判断を支援する",
            "key",
            "peak",
            2.0,
            ("PoC費用", "削減時間", "品質改善", "本番判断"),
            ("実測ROI",),
            ("未確認ROI断定",),
            "投資判断は削減時間と品質改善の両面で確認します",
            "Waterfall",
            ("requires_confirmation",),
            "意思決定",
            "ロードマップを投資判断へ接続する",
            "リスク確認へ進む",
            "ROIはPoC後の評価項目として扱う",
        ),
        _decision(
            11,
            "sec-04",
            "risk",
            "PoC前に潰すべきリスクを整理する",
            "不安点と対策を理解する",
            "リスク承認を支援する",
            "support",
            "medium",
            1.5,
            ("データ準備", "例外処理", "現場負荷", "連携"),
            ("セキュリティ詳細",),
            ("不安を煽るだけの表現",),
            "データ準備と例外処理を先に設計し、導入リスクを抑えます",
            "Risk Matrix",
            ("hypothesis", "requires_confirmation"),
            "冷静",
            "投資判断の前提としてリスクを整理する",
            "体制へつなぐ",
            "リスクを管理可能な論点として説明する",
        ),
        _decision(
            12,
            "sec-04",
            "governance",
            "役割と責任分担を示す",
            "誰が何を担うか理解する",
            "実行責任の合意を支援する",
            "support",
            "medium",
            1.5,
            ("現場", "情報システム", "Ready Crew"),
            ("承認者",),
            ("詳細RACI表",),
            "体制は現場・情報システム・Ready Crewの役割を分けます",
            "Governance",
            ("requires_confirmation",),
            "安心",
            "リスク対策を実行体制へ落とす",
            "意思決定事項へつなぐ",
            "会議後の担当者確認に使う",
        ),
        _decision(
            13,
            "sec-04",
            "decision",
            "次回合意事項を明確にする",
            "何を決めれば前に進むか理解する",
            "PoC開始判断を促す",
            "hero",
            "peak",
            1.5,
            ("PoC範囲", "評価指標", "開始条件"),
            ("次回日程",),
            ("曖昧なお願い",),
            "次回はPoC範囲・評価指標・開始条件を合意します",
            "Decision Tree",
            ("requires_confirmation",),
            "決断",
            "体制確認から次の決定へ進む",
            "Appendixは必要時のみ参照",
            "最後に何を合意したいかを明確に伝える",
        ),
        _decision(
            14,
            "sec-05",
            "appendix_evidence",
            "評価条件の詳細を保持する",
            "必要時に根拠を確認できる",
            "本編を軽くしつつ詳細確認に備える",
            "appendix",
            "low",
            0.8,
            ("測定方法", "サンプル条件", "判定基準"),
            ("詳細算定根拠",),
            ("本編での長い説明",),
            "Appendix: 評価条件の詳細",
            "Appendix Tree",
            ("requires_confirmation",),
            "冷静",
            "本編の決定後、詳細確認があれば参照する",
            "FAQへ進む",
            "質問時に補足できる材料を持つ",
            appendix_reason_if_moved="本編の意思決定には重すぎるためAppendixへ移動",
        ),
        _decision(
            15,
            "sec-05",
            "appendix_faq",
            "FAQと技術確認事項を保持する",
            "IT・現場の不安に答えられる",
            "質疑対応を支援する",
            "appendix",
            "low",
            0.7,
            ("セキュリティ", "連携", "例外処理"),
            ("詳細FAQ",),
            ("本編での技術仕様羅列",),
            "Appendix: リスク確認とFAQ",
            "FAQ Tree",
            ("requires_confirmation",),
            "冷静",
            "評価条件詳細から関連質問へ対応する",
            "本編へ戻る場合は意思決定事項を再確認する",
            "営業担当が質問に備える",
            appendix_reason_if_moved="詳細な技術・FAQは本編の流れを止めるためAppendixへ移動",
        ),
    ]
    return _adapt_to_page_budget(slides, target_count)
