"""Error codes for the Phase 2C Message Designer."""


SUPPORTED_MESSAGE_DESIGN_VERSION = "pe2_slide_message_design_v1"
SUPPORTED_MESSAGE_DESIGNER_OUTPUT_VERSION = "pe2_message_designer_output_v1"


class MessageErrorCode:
    SCHEMA_REQUIRED = "PE2-MSG-SCHEMA-001"
    SCHEMA_ENUM = "PE2-MSG-SCHEMA-002"
    SCHEMA_EXTRA = "PE2-MSG-SCHEMA-003"
    VERSION_MISMATCH = "PE2-MSG-SCHEMA-004"
    REFERENCE_MISSING = "PE2-MSG-REF-001"
    HEADLINE_EMPTY = "PE2-MSG-HEADLINE-001"
    HEADLINE_LENGTH = "PE2-MSG-HEADLINE-002"
    HEADLINE_NOUN_ONLY = "PE2-MSG-HEADLINE-003"
    MAIN_EMPTY = "PE2-MSG-MAIN-001"
    MAIN_LENGTH = "PE2-MSG-MAIN-002"
    SUPPORT_COUNT = "PE2-MSG-SUPPORT-001"
    SUPPORT_LENGTH = "PE2-MSG-SUPPORT-002"
    SUPPORT_DUPLICATE = "PE2-MSG-SUPPORT-003"
    EVIDENCE_ALIGNMENT = "PE2-MSG-EVIDENCE-001"
    EVIDENCE_MISSING = "PE2-MSG-EVIDENCE-002"
    NUMERIC_UNSUPPORTED = "PE2-MSG-NUMERIC-001"
    STYLE_MISMATCH = "PE2-MSG-STYLE-001"
    WEAK_LANGUAGE = "PE2-MSG-QUALITY-001"
    AMBIGUOUS_LANGUAGE = "PE2-MSG-QUALITY-002"
    PLACEHOLDER = "PE2-MSG-PLACEHOLDER-001"
    INTERNAL_LABEL = "PE2-MSG-SAFETY-001"
    SPEAKER_NOTE_COPY = "PE2-MSG-SAFETY-002"


class MessageDesignerError(Exception):
    """Base exception for Message Designer contract failures."""

