from __future__ import annotations

SLIDE_WIDTH_IN = 13.333
SLIDE_HEIGHT_IN = 7.5
SAFE_MARGIN_X = 0.82
SAFE_MARGIN_TOP = 0.62
SAFE_MARGIN_BOTTOM = 0.58
HEADER_HEIGHT = 0.86
FOOTER_HEIGHT = 0.34
CONTENT_TOP = 1.52
CONTENT_BOTTOM = 6.62
CONTENT_HEIGHT = CONTENT_BOTTOM - CONTENT_TOP
COLUMN_GAP = 0.28
CARD_GAP = 0.24
CARD_RADIUS_LABEL = "rounded_rectangle_shape"

SAFE_AREA = {
    "x": SAFE_MARGIN_X,
    "y": SAFE_MARGIN_TOP,
    "w": SLIDE_WIDTH_IN - SAFE_MARGIN_X * 2,
    "h": SLIDE_HEIGHT_IN - SAFE_MARGIN_TOP - SAFE_MARGIN_BOTTOM,
}
