PROPOSAL_ANALYSIS_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "project_summary",
        "assumed_customer_issues",
        "issue_priorities",
        "win_probability",
        "proposal_policy",
        "proposal_story",
        "proposal_structure",
        "slide_scripts",
        "expected_questions_and_answers",
        "quality_check",
        "powerpoint_generation_data",
    ],
    "properties": {
        "project_summary": {"type": "string"},
        "assumed_customer_issues": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["issue", "background", "evidence", "confidence"],
                "properties": {
                    "issue": {"type": "string"},
                    "background": {"type": "string"},
                    "evidence": {"type": "string"},
                    "confidence": {"type": "string"},
                },
            },
        },
        "issue_priorities": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["rank", "issue", "reason", "proposed_response"],
                "properties": {
                    "rank": {"type": "integer"},
                    "issue": {"type": "string"},
                    "reason": {"type": "string"},
                    "proposed_response": {"type": "string"},
                },
            },
        },
        "win_probability": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "rank",
                "probability",
                "label",
                "reason",
                "risk_score",
                "risk_label",
                "positive_factors",
                "risk_factors",
                "recommended_next_actions",
                "improvement_actions",
                "projected_probability_after_actions",
            ],
            "properties": {
                "rank": {"type": "string", "enum": ["A", "B", "C", "D"]},
                "probability": {"type": "integer", "minimum": 0, "maximum": 100},
                "label": {"type": "string"},
                "reason": {"type": "string"},
                "risk_score": {"type": "integer", "minimum": 1, "maximum": 5},
                "risk_label": {"type": "string"},
                "positive_factors": {"type": "array", "items": {"type": "string"}},
                "risk_factors": {"type": "array", "items": {"type": "string"}},
                "recommended_next_actions": {"type": "array", "items": {"type": "string"}},
                "improvement_actions": {"type": "array", "items": {"type": "string"}},
                "projected_probability_after_actions": {"type": "integer", "minimum": 0, "maximum": 100},
            },
        },
        "proposal_policy": {"type": "string"},
        "proposal_story": {"type": "string"},
        "proposal_structure": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["section", "objective", "key_message"],
                "properties": {
                    "section": {"type": "string"},
                    "objective": {"type": "string"},
                    "key_message": {"type": "string"},
                },
            },
        },
        "slide_scripts": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "slide_no",
                    "section",
                    "title",
                    "body",
                    "speaker_notes",
                    "visual_suggestion",
                ],
                "properties": {
                    "slide_no": {"type": "integer"},
                    "section": {"type": "string"},
                    "title": {"type": "string"},
                    "body": {"type": "array", "items": {"type": "string"}},
                    "speaker_notes": {"type": "string"},
                    "visual_suggestion": {"type": "string"},
                },
            },
        },
        "expected_questions_and_answers": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["question", "answer"],
                "properties": {
                    "question": {"type": "string"},
                    "answer": {"type": "string"},
                },
            },
        },
        "quality_check": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "logical_consistency",
                "typos",
                "proposal_coverage",
                "competitive_differentiation",
                "alignment_with_customer_issues",
                "human_review_notes",
            ],
            "properties": {
                "logical_consistency": {"type": "string"},
                "typos": {"type": "string"},
                "proposal_coverage": {"type": "string"},
                "competitive_differentiation": {"type": "string"},
                "alignment_with_customer_issues": {"type": "string"},
                "human_review_notes": {"type": "string"},
            },
        },
        "powerpoint_generation_data": {
            "type": "object",
            "additionalProperties": False,
            "required": ["deck_title", "client_name", "slides"],
            "properties": {
                "deck_title": {"type": "string"},
                "client_name": {"type": "string"},
                "slides": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": [
                            "slide_no",
                            "layout",
                            "title",
                            "bullets",
                            "speaker_notes",
                            "visual_suggestion",
                        ],
                        "properties": {
                            "slide_no": {"type": "integer"},
                            "layout": {"type": "string"},
                            "title": {"type": "string"},
                            "bullets": {"type": "array", "items": {"type": "string"}},
                            "speaker_notes": {"type": "string"},
                            "visual_suggestion": {"type": "string"},
                        },
                    },
                },
            },
        },
    },
}

