"""Deck-level error codes for Presentation Engine 2.0 Phase 1.5."""


SUPPORTED_DECK_BLUEPRINT_VERSION = "pe2_deck_blueprint_v1"


class DeckErrorCode:
    SCHEMA_REQUIRED = "PE2-DECK-SCHEMA-001"
    SCHEMA_ENUM = "PE2-DECK-SCHEMA-002"
    SCHEMA_LENGTH = "PE2-DECK-SCHEMA-003"
    SCHEMA_DUPLICATE_ID = "PE2-DECK-SCHEMA-004"
    STRUCTURE_MISSING = "PE2-DECK-STRUCTURE-001"
    STRUCTURE_ORDER = "PE2-DECK-STRUCTURE-002"
    STRUCTURE_COUNT = "PE2-DECK-STRUCTURE-003"
    STRUCTURE_REFERENCE = "PE2-DECK-STRUCTURE-004"
    NARRATIVE_ORDER = "PE2-DECK-NARRATIVE-001"
    NARRATIVE_COHERENCE = "PE2-DECK-NARRATIVE-002"
    AUDIENCE_FIT = "PE2-DECK-AUDIENCE-001"
    QUALITY_EVIDENCE = "PE2-DECK-QUALITY-001"
    QUALITY_CTA = "PE2-DECK-QUALITY-002"
    TRANSITION_MISSING = "PE2-DECK-TRANSITION-001"
    SAFETY_PLACEHOLDER = "PE2-DECK-SAFETY-001"
    SAFETY_SLIDE_REFERENCE = "PE2-DECK-SAFETY-002"


class DeckBlueprintError(Exception):
    """Base exception for deck blueprint contract failures."""
