"""Presentation Engine 2.0 Phase 3 preparation: Visual Plan Contract."""

from .contracts import (
    VISUAL_PLAN_CONTRACT_NAME,
    VISUAL_PLAN_SCHEMA_DRAFT,
    SUPPORTED_VISUAL_PLAN_CONTRACT_VERSION,
)
from .enums import (
    CalloutStrategy,
    ChartStrategy,
    ComponentCandidateType,
    DiagramStrategy,
    IconStrategy,
    ImageStrategy,
    LayoutStrategy,
    TableStrategy,
    ValidationSeverity,
    VisualConfidence,
    VisualPlanStatus,
    VisualPriorityLevel,
    VisualReadingOrder,
    VisualStrategy,
)
from .models import (
    CalloutStrategyPlan,
    ChartStrategyPlan,
    ComponentCandidate,
    DiagramStrategyPlan,
    IconStrategyPlan,
    ImageStrategyPlan,
    TableStrategyPlan,
    VisualDirectorInput,
    VisualPlanContract,
    VisualPlanItem,
    VisualPriorityPlan,
    VisualRiskFlag,
    VisualValidationIssue,
    VisualValidationResult,
)
from .schema import (
    example_visual_plan_contract,
    input_schema,
    invalid_visual_plan_examples,
    output_schema,
    schema_json,
    visual_plan_item_schema,
)
from .validators import validate_visual_plan_contract, validate_visual_plan_item

__all__ = [
    "CalloutStrategy",
    "CalloutStrategyPlan",
    "ChartStrategy",
    "ChartStrategyPlan",
    "ComponentCandidate",
    "ComponentCandidateType",
    "DiagramStrategy",
    "DiagramStrategyPlan",
    "IconStrategy",
    "IconStrategyPlan",
    "ImageStrategy",
    "ImageStrategyPlan",
    "LayoutStrategy",
    "SUPPORTED_VISUAL_PLAN_CONTRACT_VERSION",
    "TableStrategy",
    "TableStrategyPlan",
    "VISUAL_PLAN_CONTRACT_NAME",
    "VISUAL_PLAN_SCHEMA_DRAFT",
    "ValidationSeverity",
    "VisualConfidence",
    "VisualDirectorInput",
    "VisualPlanContract",
    "VisualPlanItem",
    "VisualPlanStatus",
    "VisualPriorityLevel",
    "VisualPriorityPlan",
    "VisualReadingOrder",
    "VisualRiskFlag",
    "VisualStrategy",
    "VisualValidationIssue",
    "VisualValidationResult",
    "example_visual_plan_contract",
    "input_schema",
    "invalid_visual_plan_examples",
    "output_schema",
    "schema_json",
    "validate_visual_plan_contract",
    "validate_visual_plan_item",
    "visual_plan_item_schema",
]
