from typing import Dict

from .enums import BudgetType, EvidenceLevel, Persona
from .models import ProposalStrategyInput


FIXTURES: Dict[str, ProposalStrategyInput] = {
    "image_recognition": ProposalStrategyInput(
        project_title="生花オークション向けAI画像認識導入支援",
        project_summary="商品画像から花の種類、色、等級、状態を候補判定し、担当者が最終確認する。",
        business_goals=["判定品質の安定", "確認時間の短縮"],
        current_problems=["目視確認の負荷", "担当者間の判断ばらつき"],
        proposed_solution="AI画像認識で候補を提示し、確認結果を既存システムへAPI連携する。",
        expected_deliverables=["PoC", "認識モデル検証", "連携設計"],
        integrations=["API", "商品管理システム"],
        budget="上限1000万円",
        budget_type=BudgetType.UPPER_LIMIT,
        expected_kpis=["候補正答率", "人手修正率", "確認時間"],
        stakeholders=["現場責任者", "品質保証", "情報システム"],
        audience_hint=Persona.FIELD_LEADER,
        evidence={"budget": EvidenceLevel.PROVIDED},
    ),
    "ai_ocr": ProposalStrategyInput(
        project_title="請求書AI-OCR導入",
        project_summary="帳票画像から請求日、金額、取引先を抽出し、人が確認して会計システムへCSV連携する。",
        business_goals=["入力工数削減", "転記ミス削減"],
        current_problems=["手入力が多い", "月末に処理が集中する"],
        proposed_solution="AI-OCRで候補抽出し、確認画面で修正後にCSV出力する。",
        expected_deliverables=["AI-OCR PoC", "確認UI", "CSV連携"],
        integrations=["CSV", "会計システム"],
        expected_kpis=["抽出精度", "修正率", "1件あたり確認時間"],
        stakeholders=["現場責任者", "情報システム"],
    ),
    "rpa": ProposalStrategyInput(
        project_title="受注登録RPA化",
        project_summary="メール添付の受注情報を基幹システムへ登録する定型業務をRPAで自動化する。",
        business_goals=["作業時間短縮", "入力漏れ削減"],
        current_problems=["反復入力", "例外処理の属人化"],
        proposed_solution="ボットが定型登録を行い、例外だけ人に戻す。",
        expected_deliverables=["RPAシナリオ", "例外処理設計", "運用手順"],
        expected_kpis=["自動処理率", "例外率", "処理時間"],
        stakeholders=["課長", "現場担当者"],
    ),
    "chatbot": ProposalStrategyInput(
        project_title="社内問い合わせAIチャットボット",
        project_summary="人事・総務への問い合わせをチャットボットで一次回答し、必要時に担当者へエスカレーションする。",
        business_goals=["問い合わせ対応時間削減", "回答品質の標準化"],
        current_problems=["同じ質問が多い", "回答が担当者ごとに異なる"],
        proposed_solution="FAQと会話ログをもとに回答候補を提示する。",
        expected_deliverables=["チャットボット", "FAQ整備", "エスカレーション設計"],
        expected_kpis=["一次解決率", "担当者対応件数", "回答満足度"],
        stakeholders=["人事部", "現場利用者"],
    ),
    "knowledge_search": ProposalStrategyInput(
        project_title="社内ナレッジ検索",
        project_summary="社内文書と規程を横断検索し、根拠となる引用を示して回答候補を提示する。",
        business_goals=["探索時間削減", "判断根拠の明確化"],
        current_problems=["必要な資料が見つからない", "古い資料を参照してしまう"],
        proposed_solution="RAG型ナレッジ検索でソース付き回答を提供する。",
        expected_deliverables=["検索基盤", "文書取込", "権限設計"],
        expected_kpis=["検索成功率", "回答採用率", "探索時間"],
        stakeholders=["情報システム", "各部門"],
    ),
    "crm": ProposalStrategyInput(
        project_title="CRM営業活動管理",
        project_summary="顧客情報、商談、フォローアップをCRMで一元管理し、次の営業行動を見える化する。",
        business_goals=["営業活動の標準化", "商談停滞の削減"],
        current_problems=["顧客情報が分散", "フォロー漏れがある"],
        proposed_solution="CRM/SFAでパイプラインと活動履歴を管理する。",
        expected_deliverables=["CRM設定", "営業プロセス設計", "利用定着支援"],
        expected_kpis=["商談更新率", "フォロー完了率", "案件化率"],
        stakeholders=["営業部長", "営業担当"],
    ),
    "generative_ai": ProposalStrategyInput(
        project_title="生成AI導入支援",
        project_summary="社内文書作成と議事録作成に生成AIを導入し、プロンプトとレビューの運用ルールを整える。",
        business_goals=["作成時間短縮", "AI利用統制"],
        current_problems=["個人利用がばらばら", "レビュー基準が不明確"],
        proposed_solution="生成AIワークベンチとガバナンスを導入する。",
        expected_deliverables=["利用ルール", "プロンプト設計", "教育"],
        expected_kpis=["作成時間", "レビュー差戻し率", "利用率"],
        stakeholders=["役員", "情報システム"],
    ),
    "web_renewal": ProposalStrategyInput(
        project_title="コーポレートサイトリニューアル",
        project_summary="情報が古くスマートフォンで見づらいWebサイトを、CMSと導線設計を含めて刷新する。",
        business_goals=["問い合わせ増加", "採用強化"],
        current_problems=["サイトマップが分かりにくい", "SEOとCMS更新が弱い"],
        proposed_solution="UX設計、CMS導入、SEO基盤、問い合わせ導線改善を行う。",
        expected_deliverables=["Webサイト", "CMS", "サイトマップ", "運用マニュアル"],
        expected_kpis=["CV数", "検索流入", "更新頻度"],
        stakeholders=["広報", "営業"],
    ),
    "ai_ocr_rpa": ProposalStrategyInput(
        project_title="AI-OCRとRPAによる帳票処理自動化",
        project_summary="帳票をAI-OCRで読み取り、RPAで基幹システムへ登録する。例外は人が確認する。",
        business_goals=["処理時間短縮", "入力品質安定"],
        current_problems=["手入力と転記が多い", "例外処理が遅い"],
        proposed_solution="AI-OCR抽出、確認UI、RPA登録を組み合わせる。",
        expected_deliverables=["AI-OCR PoC", "RPAシナリオ", "例外処理設計"],
        expected_kpis=["抽出精度", "自動登録率", "例外率"],
        stakeholders=["現場責任者", "情報システム"],
    ),
    "crm_generative_ai": ProposalStrategyInput(
        project_title="CRMと生成AIによる営業支援",
        project_summary="CRMの顧客情報と商談履歴をもとに、生成AIがフォロー文面と提案ドラフトを作成する。",
        business_goals=["営業対応スピード向上", "提案品質の均一化"],
        current_problems=["フォロー文面作成に時間がかかる", "商談履歴の活用が弱い"],
        proposed_solution="CRM連携と生成AIドラフト作成を組み合わせる。",
        expected_deliverables=["CRM連携", "生成AIテンプレート", "レビュー運用"],
        expected_kpis=["フォロー作成時間", "提案作成時間", "採用率"],
        stakeholders=["営業部長", "営業担当"],
    ),
    "web_chatbot": ProposalStrategyInput(
        project_title="WebサイトとAIチャットボット導入",
        project_summary="Webサイトをリニューアルし、問い合わせ導線にAIチャットボットを配置する。",
        business_goals=["問い合わせ対応品質向上", "CV改善"],
        current_problems=["問い合わせ導線が分かりにくい", "同じ質問が多い"],
        proposed_solution="UX改善、CMS更新、チャットボット一次回答を導入する。",
        expected_deliverables=["Webサイト", "CMS", "チャットボット", "FAQ設計"],
        expected_kpis=["CV数", "一次回答率", "離脱率"],
        stakeholders=["広報", "営業"],
    ),
    "generic_consulting": ProposalStrategyInput(
        project_title="業務改善に向けた現状整理",
        project_summary="複数部門の課題を整理し、改善テーマと優先順位を決めたい。",
        business_goals=["課題整理", "実行計画策定"],
        current_problems=["課題が散在", "意思決定が進まない"],
        proposed_solution="現状ヒアリングと改善ロードマップを作成する。",
        expected_deliverables=["課題整理", "ロードマップ", "実行計画"],
        expected_kpis=["優先度合意", "実行テーマ数"],
        stakeholders=["部長", "課長"],
    ),
    "sparse": ProposalStrategyInput(project_title="AI相談"),
    "budget_only": ProposalStrategyInput(
        project_title="新規システム導入",
        project_summary="予算は500万円です。",
        budget="500万円",
    ),
    "qa_owner": ProposalStrategyInput(
        project_title="品質保証向け検査標準化",
        project_summary="品質保証部が検査基準のばらつきと監査記録不足を改善したい。",
        business_goals=["品質安定", "監査対応"],
        current_problems=["判定ばらつき", "履歴不足"],
        proposed_solution="確認履歴と承認ログを残す検査支援システムを導入する。",
        expected_kpis=["判定一致率", "監査カバー率"],
        stakeholders=["品質保証責任者"],
    ),
    "executive_roi": ProposalStrategyInput(
        project_title="経営層向けAI投資判断",
        project_summary="全社の作業時間削減と投資回収を評価し、AI導入の優先領域を決める。",
        business_goals=["ROI確認", "投資判断"],
        current_problems=["効果が見えない", "優先順位が決まらない"],
        proposed_solution="業務棚卸しとPoCで投資効果を評価する。",
        expected_kpis=["削減時間", "投資回収期間"],
        stakeholders=["経営層", "役員"],
        audience_hint=Persona.EXECUTIVE,
    ),
    "it_security": ProposalStrategyInput(
        project_title="情報システム向けセキュリティ重視AI導入",
        project_summary="社内AI利用を安全に管理し、SSO、権限、監査ログを含めた統制を行う。",
        business_goals=["安全なAI利用", "統制"],
        current_problems=["個人利用のリスク", "監査ログ不足"],
        proposed_solution="権限管理、ログ、利用ルールを備えたAI基盤を整備する。",
        expected_kpis=["管理対象利用率", "監査ログ取得率"],
        stakeholders=["情報システム", "セキュリティ担当"],
    ),
    "field_operations": ProposalStrategyInput(
        project_title="現場業務改善",
        project_summary="現場担当者の日次確認作業と報告作成を減らしたい。",
        business_goals=["作業負荷削減"],
        current_problems=["日次作業が多い", "報告が遅い"],
        proposed_solution="入力テンプレートと自動集計で報告作成を支援する。",
        expected_kpis=["作業時間", "報告遅延件数"],
        stakeholders=["現場責任者", "課長"],
    ),
    "same_project_executive": ProposalStrategyInput(
        project_title="AI-OCR導入",
        project_summary="帳票読取と人の確認で処理を効率化する。",
        business_goals=["投資判断", "工数削減"],
        current_problems=["手入力が多い"],
        proposed_solution="AI-OCRと確認UIを導入する。",
        expected_deliverables=["PoC", "確認UI"],
        expected_kpis=["削減時間", "抽出精度"],
        stakeholders=["役員"],
        audience_hint=Persona.EXECUTIVE,
    ),
    "prohibited_term_mixed": ProposalStrategyInput(
        project_title="AI-OCR導入",
        project_summary="帳票読取の提案だが、参考としてCMS更新やSEO改善という語も混在している。",
        business_goals=["帳票処理改善"],
        current_problems=["読取精度が不安定"],
        proposed_solution="AI-OCRで抽出し、人が確認する。",
        expected_kpis=["抽出精度"],
        stakeholders=["現場責任者"],
    ),
}
