from __future__ import annotations

from .enums import BudgetType, Persona
from .models import ProposalStrategyInput


SALES_STRATEGY_FIXTURES: dict[str, ProposalStrategyInput] = {
    "web_creation": ProposalStrategyInput(
        project_title="Corporate website renewal",
        project_summary="The current website is hard to update, mobile readability is poor, and inquiry flow is unclear.",
        industry="BtoB services",
        business_goals=["increase qualified inquiries", "standardize content operation"],
        current_problems=["CMS operation is slow", "SEO and conversion measurement are unclear"],
        proposed_solution="Renew the website with CMS, improved customer journey, and measurement design.",
        expected_deliverables=["website renewal", "CMS setup", "analytics plan"],
        schedule="launch in three months",
        budget="5,000,000 JPY upper limit",
        budget_type=BudgetType.UPPER_LIMIT,
        expected_kpis=["qualified inquiries", "conversion rate", "content update lead time"],
        stakeholders=["marketing", "sales"],
        audience_hint=Persona.SALES,
    ),
    "ec": ProposalStrategyInput(
        project_title="EC conversion improvement",
        project_summary="The EC site has many visits but low repeat purchase and cart completion.",
        industry="Retail",
        business_goals=["increase sales", "improve repeat purchase"],
        current_problems=["cart abandonment", "campaign operations are manual"],
        proposed_solution="Improve customer journey, CRM flow, and purchase analysis.",
        expected_deliverables=["journey analysis", "CRM scenario", "KPI dashboard"],
        schedule="next quarter",
        budget="reference budget 3,000,000 JPY",
        budget_type=BudgetType.REFERENCE,
        expected_kpis=["conversion rate", "repeat purchase rate", "average order value"],
        stakeholders=["marketing", "EC operation"],
    ),
    "recruiting": ProposalStrategyInput(
        project_title="Recruiting site and candidate communication improvement",
        project_summary="Applications are decreasing and candidate follow-up varies by recruiter.",
        industry="Recruiting",
        business_goals=["increase applications", "improve candidate experience"],
        current_problems=["weak employer brand", "follow-up is inconsistent"],
        proposed_solution="Improve recruiting story, site content, and communication templates.",
        expected_deliverables=["recruiting site plan", "message framework", "operation guide"],
        expected_kpis=["applications", "interview conversion", "candidate satisfaction"],
        stakeholders=["HR", "recruiting manager"],
        audience_hint=Persona.DEPARTMENT_HEAD,
    ),
    "ai_adoption": ProposalStrategyInput(
        project_title="AI adoption support for document creation",
        project_summary="The client wants to use generative AI for internal documents while keeping review and governance.",
        industry="Professional services",
        business_goals=["reduce drafting time", "control AI usage"],
        current_problems=["review rules are unclear", "individual usage is inconsistent"],
        proposed_solution="Introduce AI workflow, prompt templates, and review rules.",
        expected_deliverables=["AI workflow", "prompt templates", "governance guide"],
        schedule="PoC first",
        expected_kpis=["draft time", "review return rate", "approved usage rate"],
        stakeholders=["executive", "information systems"],
        audience_hint=Persona.EXECUTIVE,
    ),
    "dx": ProposalStrategyInput(
        project_title="DX roadmap for operational standardization",
        project_summary="Multiple departments manage work differently and leadership wants a phased DX roadmap.",
        industry="Manufacturing",
        business_goals=["standardize operation", "decide investment priority"],
        current_problems=["data is scattered", "approval process is slow"],
        proposed_solution="Create a roadmap, process map, and phased implementation plan.",
        expected_deliverables=["DX roadmap", "priority matrix", "implementation plan"],
        schedule="six month roadmap",
        expected_kpis=["process lead time", "manual work count", "approval cycle time"],
        stakeholders=["executive", "department heads", "information systems"],
        audience_hint=Persona.EXECUTIVE,
    ),
    "branding": ProposalStrategyInput(
        project_title="Branding renewal for new service launch",
        project_summary="The client is launching a new service and needs a clearer value message and visual direction.",
        industry="SaaS",
        business_goals=["increase recognition", "clarify value proposition"],
        current_problems=["message is inconsistent", "competitors look similar"],
        proposed_solution="Define positioning, brand message, and launch communication plan.",
        expected_deliverables=["positioning", "message guide", "launch materials"],
        expected_kpis=["brand recall", "lead quality", "campaign response"],
        stakeholders=["marketing", "executive"],
        audience_hint=Persona.EXECUTIVE,
    ),
}
